# Generated by Django 5.2.9 on 2025-12-27 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'db_table': 'Marcas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modelos',
            fields=[
                ('id_modelo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_modelo', models.CharField(max_length=50)),
                ('id_marca', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.CASCADE, to='core.marcas')),
            ],
            options={
                'verbose_name_plural': 'Modelos',
                'db_table': 'Modelos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vehiculos',
            fields=[
                ('placa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('propietario', models.CharField(blank=True, max_length=100, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('modelo_ia', models.ForeignKey(db_column='id_modelo', on_delete=django.db.models.deletion.PROTECT, to='core.modelos')),
            ],
            options={
                'verbose_name_plural': 'Vehiculos',
                'db_table': 'Vehiculos',
            },
        ),
        migrations.CreateModel(
            name='Diagnosticos',
            fields=[
                ('id_diagnostico', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
                ('ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('descripcion_sintomas', models.TextField(blank=True, null=True)),
                ('sensor_rpm', models.FloatField(blank=True, null=True)),
                ('sensor_presion_aceite', models.FloatField(blank=True, null=True)),
                ('sensor_temperatura_motor', models.FloatField(blank=True, null=True)),
                ('sensor_voltaje_bateria', models.FloatField(blank=True, null=True)),
                ('sensor_velocidad', models.FloatField(blank=True, null=True)),
                ('sensor_nivel_combustible', models.FloatField(blank=True, null=True)),
                ('ia_falla_predicha', models.CharField(blank=True, max_length=100, null=True)),
                ('ia_subfalla_predicha', models.CharField(blank=True, max_length=100, null=True)),
                ('solucion_predicha', models.TextField(blank=True, null=True)),
                ('gravedad_predicha', models.CharField(blank=True, max_length=50, null=True)),
                ('ia_confianza', models.FloatField(blank=True, null=True)),
                ('es_correcto', models.BooleanField(blank=True, null=True)),
                ('falla_real', models.CharField(blank=True, max_length=100, null=True)),
                ('subfalla_real', models.CharField(blank=True, max_length=100, null=True)),
                ('gravedad_real', models.CharField(blank=True, max_length=50, null=True)),
                ('solucion_real', models.TextField(blank=True, null=True)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('placa_ref', models.ForeignKey(blank=True, db_column='placa', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vehiculos')),
            ],
            options={
                'verbose_name_plural': 'Diagnosticos',
                'db_table': 'Diagnosticos',
            },
        ),
    ]
