# Generated by Django 5.2.9 on 2026-01-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_diagnosticos_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosticos',
            name='sensor_nivel_combustible',
        ),
        migrations.RemoveField(
            model_name='diagnosticos',
            name='sensor_presion_aceite',
        ),
        migrations.RemoveField(
            model_name='diagnosticos',
            name='sensor_rpm',
        ),
        migrations.RemoveField(
            model_name='diagnosticos',
            name='sensor_temperatura_motor',
        ),
        migrations.RemoveField(
            model_name='diagnosticos',
            name='sensor_velocidad',
        ),
        migrations.RemoveField(
            model_name='diagnosticos',
            name='sensor_voltaje_bateria',
        ),
    ]
